import React from 'react';
import { Modal, View, Text, StyleSheet, TouchableOpacity, ScrollView } from 'react-native';

interface DisclaimerModalProps {
  visible: boolean;
  onAccept: () => void;
}

const DisclaimerModal: React.FC<DisclaimerModalProps> = ({ visible, onAccept }) => {
  return (
    <Modal
      visible={visible}
      animationType="slide"
      transparent={true}
    >
      <View style={styles.overlay}>
        <View style={styles.container}>
          <ScrollView contentContainerStyle={styles.scrollContent}>
            <Text style={styles.title}>Important Notice</Text>
            <Text style={styles.text}>
              This application has not been reviewed or approved by the U.S. Food and Drug Administration (FDA). It is an experimental tool that uses artificial intelligence to generate recommendations for diabetes care based on the data you provide. The quality and accuracy of its advice depend entirely on the accuracy and completeness of your input.
              {'\n\n'}
              The information, suggestions, and recommendations generated by this app are for informational purposes only and are not a substitute for professional medical advice, diagnosis, or treatment. Always consult with a qualified healthcare provider or endocrinologist before making any changes to your diabetes management plan. Do not disregard, avoid, or delay obtaining medical advice from your healthcare provider because of something you have read or interpreted from this app.
              {'\n\n'}
              By clicking "Accept," you acknowledge that you understand the experimental nature of this app, accept all risks associated with its use, and agree not to hold the developers or distributors liable for any harm or damages resulting from its use.
            </Text>
            <TouchableOpacity style={styles.acceptButton} onPress={onAccept}>
              <Text style={styles.acceptText}>Accept</Text>
            </TouchableOpacity>
          </ScrollView>
        </View>
      </View>
    </Modal>
  );
};

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 24,
    margin: 24,
    maxHeight: '85%',
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 16,
    textAlign: 'center',
  },
  text: {
    fontSize: 16,
    marginBottom: 24,
    color: '#333',
    textAlign: 'left',
  },
  acceptButton: {
    backgroundColor: '#007AFF',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  acceptText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
});

export default DisclaimerModal;
