"""Add quality column to glucose_readings

Revision ID: d548a4f6e576
Revises: 
Create Date: 2025-08-08 16:44:48.849272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd548a4f6e576'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('glucose_readings', sa.Column('quality', sa.String(), nullable=True))
    op.add_column('glucose_readings', sa.Column('trend', sa.String(), nullable=True))
    op.add_column('glucose_readings', sa.Column('trend_rate', sa.Float(), nullable=True))
    op.add_column('glucose_readings', sa.Column('is_high_alert', sa.Boolean(), nullable=True))
    op.add_column('glucose_readings', sa.Column('is_low_alert', sa.Boolean(), nullable=True))
    op.add_column('glucose_readings', sa.Column('is_urgent_low', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('glucose_readings', 'is_urgent_low')
    op.drop_column('glucose_readings', 'is_low_alert')
    op.drop_column('glucose_readings', 'is_high_alert')
    op.drop_column('glucose_readings', 'trend_rate')
    op.drop_column('glucose_readings', 'trend')
    op.drop_column('glucose_readings', 'quality')
    # ### end Alembic commands ###
